name: Vercel Development Deploy

on:
  pull_request:
    branches: [development]
  push:
    branches: [development]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - run: npm install
      
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
        
      - name: Pull Vercel environment
        run: |
          vercel pull --yes --environment=development \
          --token=${{ secrets.VERCEL_TOKEN }} \
          --scope=${{ secrets.VERCEL_SCOPE }}
          
      - name: Build project
        run: |
          vercel build --prod=false \
          --token=${{ secrets.VERCEL_TOKEN }} \
          --scope=${{ secrets.VERCEL_SCOPE }}
          
      - name: Create deployment
        run: |
          vercel deploy --prebuilt \
          --token=${{ secrets.VERCEL_TOKEN }} \
          --scope=${{ secrets.VERCEL_SCOPE }}
